{
 "title": "Local Servers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Var Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (\r\n  (node_filesystem_avail_bytes{job=\"root_space\", mountpoint=\"/\", fstype!~\"tmpfs|overlay\", device!~\"rootfs\"} * 100)\r\n  / node_filesystem_size_bytes{job=\"root_space\", mountpoint=\"/\", fstype!~\"tmpfs|overlay\", device!~\"rootfs\"}\r\n)\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (\n  (node_filesystem_avail_bytes{job=\"root_space\", mountpoint=\"/\", fstype!~\"tmpfs|overlay\", device!~\"rootfs\"} * 100)\n  / node_filesystem_size_bytes{job=\"root_space\", mountpoint=\"/\", fstype!~\"tmpfs|overlay\", device!~\"rootfs\"}\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memorey Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{job=\"mem_usage\"} * 100 / node_memory_MemTotal_bytes{job=\"mem_usage\"})\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LoadAverage [1 MIN]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"load_average\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}